

#ifdef RCSID
static const char *const rcsid
= "@(#)$Id: mkassym.c,v 1.2 1999/07/02 22:04:10 jaw Exp $";
#endif


#include <sys/types.h>
#include <sys/param.h>
#include <conf.h>
#include <proc.h>
#include <error.h>


#define offsetof(type, member) ((size_t)(&((type *)0)->member))


main(){
    printf("/* AUTOGENERATED FILE -- DO NOT EDIT */\n");
    printf("/* generated by mkassym */\n");
    printf("#define PROC_SP %d\n", offsetof(struct Proc, sp));

#ifdef PLATFORM_EMUL
    printf("#define PLATFORM_EMUL\n");
#endif
#ifdef USE_PROC
    printf("#define USE_PROC\n");
#endif
	exit(0);
}
