
AS = as $(CONF_FLAGS)
LD = gcc -m32
CC = gcc -m32
LINK = gcc -m32
OBJCOPY = objcopy
LIBS = -lm
CFLAGS = -g -fno-builtin

INCL_FLAGS = -I../../src/machdep/i386/common/inc -I../../src/machdep/i386/common/inc

